//    public class App {
//        public static void main(String[] args) {
//            try {
//            } catch (Exception e) {
//
//            } catch (ArithmeticException a) {
//
//            }
//        }
//    }


// El codigo no es correcto, ya que se utiliza un bloque catch de una superclase antes que el catch de una subclase
// Causando que el bloque catch de la subclase nunca se ejecute, siendo todas la excepciones controladas por la superclase
// Tambien provoca un error de compilacion ya que la sintaxis es incorrecta

